import praw
import datetime

SUBREDDIT_NAME = "wub_wub"
USERNAME = "wub_wub"
PASSWORD = "*******"
USER_AGENT = "/r/learnpython css update script author: /u/wub_wub"


def update_stylesheet():
    reddit = praw.Reddit(user_agent=USER_AGENT)
    reddit.login(USERNAME, PASSWORD)
    full_stylesheet = "/* Generated by update.py on: {} */\n\n".format(
        datetime.datetime.now().isoformat())
    with open("stylesheet.css", "r") as main_stylesheeet:
        full_stylesheet += main_stylesheeet.read()
    with open("flairs_stylesheet.css", "r") as flair_stylesheet:
        full_stylesheet += flair_stylesheet.read()
    subreddit = reddit.get_subreddit(SUBREDDIT_NAME)
    try:
        response = reddit.set_stylesheet(subreddit, full_stylesheet)
        if response['errors'] != []:
            print "Updating failed"
            print response['errors']
    except praw.errors.BadCSS:
        print "Invalid CSS"


if __name__ == '__main__':
    prompt = raw_input("Are you sure you want to update CSS? Y/N")

    if prompt.upper() == "Y":
        update_stylesheet()
    else:
        raw_input("Updating CSS canceled, press return to texit")
